# Generated by Django 4.1.9 on 2023-06-29 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OatmilkResponse",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_time", models.DateField()),
                ("drinks_oatmilk", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("zip_code", models.IntegerField()),
                ("store", models.CharField(max_length=100)),
                ("oat_milk_quantity", models.IntegerField()),
            ],
        ),
    ]
