# Generated by Django 4.1.9 on 2023-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oatmilkresponse",
            name="store_name",
        ),
        migrations.AlterField(
            model_name="oatmilkresponse",
            name="zip_code",
            field=models.CharField(max_length=5),
        ),
    ]
